### ISSUE TITLE
No data published

### ISSUE THREAD

**Issue by alrad32** [SICKAG/sick_visionary_ros#3]
### Prerequisites

Put an X between the brackets on this line if you have done all of the following:
* [X] Checked that your issue isn't already filed

### Current Behavior:
I cloned the repo and followed the installation instructions. I changed the IP address in the launch file to match that of my camera (visionary t-mini). When firing the launch file, the communication is successful with the camera. However, no data is being published on any of the topics. 
I tried installing the ros driver available [here](https://prod.sick.com/au/en/downloads/software?q=:typ1:Driver:typ2:ROS%2520driver:Def_Type:Download) and worked perfectly out of the box with exactly the same setup. I am running all nodes locally.
So, is this repo stable so far?

### Versions/Environmen- 
- OS: Ubuntu 20.04
- ROS: Noetic

**Comment by zimmefaSICKAG** [comment]
We have looked into this issue and have identified the cause for this behaviour. We are currently working on a solution.
Are you working with the binaries or do you build the driver by yourself based on the code in the repo?

**Comment by alrad32** [comment]
Hello,
I build the driver myself as per the installation guidelines in the repo Readme

**Comment by peichtoSICKAG** [comment]
Hello alrad32,
our first public release was indeed newer than the one you mentioned.
The problem was introduced by the fact that the driver now stops streaming per default, when no topic is subscribed.
With this change for the Visionary-T mini a session timeout in the shared code was not correctly handled and thus the node was unable to control the camera when there were more than 5s between startup and first subscriber.
This was now fixed in the shared code 2.5.0 and integraded with 1.1.2 for the ROS code.
Please test this new version, the updated binaries will still take some propagation time.

**Comment by peichtoSICKAG** [comment]
no further response - considering fixed.

**Comment by amal-k-ajay** [comment]
Hello,
I'm facing the same issue. I tried with the new version of shared code 2.5.0 and is still not able to get any data from the device. I changed the IP address to match my camera and the connection got established. I started rviz with fixed frame under Global Options as "camera" and subscribed to the topics.
![1](https://github.com/user-attachments/assets/0323e839-956c-4215-bc97-ab3c5e58d4f7)

**Comment by xfealal** [comment]
Hello @amal-k-ajay,

I was unable to replicate the issue on my end (Ubuntu 20.04, ROS Noetic, Camera firmware version 2.1.0). I suspect this might be a specific issue with your camera rather than a problem with the ROS driver itself.
It could be related to your camera’s configuration, connection, or other factors.

To help us assist you better, please provide the following information:

- The firmware version your camera is running.
- The environment in which you are operating the camera.

Best regards

**Comment by amal-k-ajay** [comment]
Hello @xfealal ,
Thanks for the reply, The camera firmware version is 3.11.2.1 ( SDD version 2.1.0.3341R ) and I'm working on Ubuntu 20.04.6 LTS with ROS Noetic.

**Comment by amal-k-ajay** [comment]
Hello @xfealal ,

Were you able to replicate the issue? I tried downgrading the camera firmware to 2.1.0 using the SOPAS ET software and it didn't work. I'm not sure if the downgrading actually worked because it showed "xxxxxx" instead of the version number which previously showed "3.11.2.1".

I followed the steps mentioned in the [support portal](https://support.sick.com/sick-knowledgebase/article/?code=KA-07773) using the firmware from [here](https://www.sick.com/de/de/catalog/digitale-dienste-und-software/software/firmware-visionary-t-mini-cx/p/p677442).

**Comment by xfealal** [comment]
Hello @amal-k-ajay, 
I'm sorry to hear that you're still facing this issue. I was unable to replicate the issue with **camera firmware version is 3.11.2.1 ( SDD version 2.1.0.3341R ) and Ubuntu 20.04.6 LTS with ROS Noetic**. The camera firmware is definetly not the issue here.

I suggest the following steps:
1. Install The CX firmware version 2.1.0 as mentioned [here](https://support.sick.com/sick-knowledgebase/article/?code=KA-07773). Just make sure the SDD version is 2.1.0.3341R.
2. Follow all the Installation steps as mentioned in the [README](https://github.com/SICKAG/sick_visionary_ros/blob/main/README.md) i.e. new workspace, fresh clone, build and source.
3. Launch the driver with the launchfile (make sure to change the **IP**) 
4. Share the console output after launching, if the Issue still persists.

**Comment by amal-k-ajay** [comment]
Hello @xfealal ,

Thank you for your help. I figured it out. It's working now. The issue was that my ip was set to 169.254.174.161:2122 in the SOPAS tool so I was changing the API-port from default 2114 to 2122 in the cpp file. Even though the device got connected it was not reading the data. I then changed it back to the 2114 and followed the same steps. It's working now.

**Comment by xfealal** [comment]
I'm glad to hear that you resolved the issue. 
Best regards.
